version: "3.9"
services:
  frontend:
    build: ./frontend
    ports: 
      - "5173:5173"
    depends_on:
      - api-gateway
    
  api-gateway:
    build: ./backend/api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - authenticationservice
      - chatservice
    
  authenticationservice:
    build: ./backend/services/authenticationService
    ports:
      - "4000:4000"
    
  chatservice:
    build: ./backend/services/chatService
    ports:
      - "4001:4000"
    


